name: Issue

on: 
    push: 
    # issues:
    #     types: [opened, edited]

jobs:
    to-do:
        name: 'Add issue to project with TO DO state'
        runs-on: ubuntu-latest
        steps:
            - name: CONTEXT
              run: echo '${{ toJson(github) }}'